### ISSUE TITLE
Publish latest version to npm

### ISSUE THREAD

**Issue by binarykitchen** [mcollina/node-errormailer#19]
Ciao @mcollina 

Just pushed a commit which bumps some packages, see 
https://github.com/mcollina/node-errormailer/commit/1db6f4092e379bf2a406ea8c5c9f75ad9e355e10

All tests pass and backward compatibility is safe.

If you have no objections, how about a version bump to 1.0.1 and publish that to npm?

**Comment by mcollina** [comment]
I've added you to the owners of this module on npm :).

**Comment by mcollina** [comment]
Release when you are ready to go!

**Comment by binarykitchen** [comment]
cool, done, v1.0.1 is npm-published
